### ISSUE TITLE
Milestone v0.4.0

### ISSUE THREAD

**Issue by dchertousov** [Travelport-Ukraine/uapi-json#25]
We should resolve next issues before releasing 0.4.0

- [x] Replace error handling with node-error-helpers #23 
- [x] Change services export #27
- [x] Uapi parser should choose version automatically #29
- [x] Change hotels service parser #28
- [x] Move XMLTemplates to services folders. #31
- [x] Change babel config. #32

**Comment by shmuga** [comment]
@dchertousov I think we are ready for release 0.4.0.

**Comment by dchertousov** [comment]
🎉
